apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic
spec:
  build:
    env:
    - name: BP_MAVEN_POM_FILE
      value: skip-pom.xml
  source:
    git:
      url: https://github.com/sample-accelerators/spring-petclinic.git
      ref:
        branch: main
